AWSTemplateFormatVersion: '2010-09-09' 
Parameters: 
  ProjectName: 
    Type: String 
    Default: DemoCloudformation 
  VpcCidr: 
    Type: String 
    Default: 10.0.0.0/16 
Resources: 
  VPC: 
    Type: AWS::EC2::VPC 
    Properties: 
      CidrBlock: !Ref VpcCidr 
      EnableDnsHostnames: true 
      EnableDnsSupport: true 
      Tags: 
        - Key: Name 
          Value: !Sub "${ProjectName}_Vpc"
