name: Deploy EKS Cluster
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      EKS_CLUSTER_TEMPLATE: eks-cluster.yaml
      EKS_CLUSTER_STACK_NAME: DemoEksClusterTemplate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy EKs Cluster to CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.EKS_CLUSTER_STACK_NAME }}
          template: ${{ env.EKS_CLUSTER_TEMPLATE }}
          no-fail-on-empty-changeset: "1"
