name: Deploy CloudFormation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPC_DEMO_TEMPLATE: DemoVpcCloudformation.yaml
      VPC_DEMO_STACK_NAME: DemoVpcCloudformation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEYID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Deploy Template to CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.VPC_DEMO_STACK_NAME }}
          template: ${{ env.VPC_DEMO_TEMPLATE }}
          no-fail-on-empty-changeset: "1"
